### PR TITLE
Fix deprecation warning in alchemist-server

### LINKED ISSUE #45: Autocompletion on elixir 1.4 not working
I am a bit at a loss regarding how to fix this. The plugin is working flawless on Windows, but on Linux (Mint 18.1, Elixir 1.4) the autocompletion does not work.
Tried to things to find out whats wrong:
1. Started the alchemist-server which comes along with the plugin. It produces a lot of warnings and the code examples shown on the github page are not working. Example:
```
COMP { "def", [ context: Elixir, imports: [Enum], aliases: [{MyList, List}] ] }
Server Error: 
no match of right hand side value: {{"def", [context: Elixir, imports: [Enum], aliases: [{MyList, List}]]}, []}
    lib/api/comp.exs:42: Alchemist.API.Comp.normalize/1
    lib/api/comp.exs:15: Alchemist.API.Comp.request/1
    lib/server.exs:59: Alchemist.Server.run/6
    lib/server.exs:39: Alchemist.Server.loop/5
    (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
    (elixir) src/elixir_compiler.erl:30: :elixir_compiler.quoted/3
    (elixir) lib/code.ex:370: Code.require_file/2
```
2. Cloned the code from the alchemist-server gist. Did the same thing and it works as expected.

### PR DESCRIPTION
**Pull request by fr1zle**
This fixes #45

(Damn, new machine and didnt set up gitconfig yet, if you want me to redo @mat-mcloughlin let me know)

### CODE REVIEW

**Comment by fr1zle** [comment]
This should be pulled with/after #24 i guess

**Comment by mat-mcloughlin** [comment]
Same for this. Should this be a PR submitted to alchemist. Then we can pull in the latest version.

I was considering the idea of submoduling it so we can keep up to date

**Comment by fr1zle** [comment]
@mat-mcloughlin yes, this would be ideal, but afaik the API changed and so the way we currently call alchemist-server wont work. When I started implementing the features i found this out and chose the version used by atom-elixir instead.

**Comment by mat-mcloughlin** [comment]
Ah ok,

I'll pull these in then but do you think there is any advantage to moving to the latest version of alchemist?

**Comment by fr1zle** [comment]
I think it would be nice to be able to just use the upstream version, yeah.
I will try open up an issue for that detailing the changes in the API

**Comment by mat-mcloughlin** [comment]
Pulling this in for now until we figure out a better way to handle alchemist

**Pull request merged**
