### PR TITLE
Implemented autocomplete and goto-definition

### LINKED ISSUE #2: Bring autocomplete to the vscode
Thanks for getting Elixir support into VSCode!

How about joining forces with https://github.com/wende/autocomplete-elixir/issues/40 and bring auto-complete as well?

### PR DESCRIPTION
**Pull request by fr1zle**
This implementation uses https://github.com/tonini/alchemist-server
and is heavily inspired by https://github.com/msaraiva/atom-elixir.

It probably is not perfect yet and i have not tested it in a longer session, but for now it seems to work fine.

closes #2

### CODE REVIEW

**Comment by gerred** [comment]
Can this be merged? @fr1zle how can I test this as well?

**Comment by Hades32** [comment]
@mat-mcloughlin when will we see this in master? :) 
Is something needed?

**Comment by fr1zle** [comment]
I think the current pull can not be build. It does however run in the debugger. I have a building version on my local computer, but I won't be able to reach it before Saturday due to some health issues. 
If you (@mat-mcloughlin) don't feel like maintaining this or don't have the time currently, I would be fine with assisting you or even take over!

**Comment by shersh** [comment]
Hi guys! Any news about code completion?

**Comment by mat-mcloughlin** [comment]
Looking through the PR as we speak @shersh 

 @fr1zle assistance would be appreciated as time is low at the moment. Perhaps we can set up a call to chat about it?

**Comment by fr1zle** [comment]
I fixed the issues with this pull and added some other fixes (intendation and highlighting) in html.eex files on this branch: https://github.com/fr1zle/vscode-elixir/tree/proper

I attached a build version of this for everyone to test: 
[vscode-elixir-0.0.6-dev.zip](https://github.com/mat-mcloughlin/vscode-elixir/files/271982/vscode-elixir-0.0.6-dev.zip)

This basically removed all the work done prior to this, i hope this is not an issue :/

@mat-mcloughlin where would you like to chat? my skype is 'fr1zle' as well :)

**Comment by shersh** [comment]
@fr1zle thx for work, it works (=

**Comment by mat-mcloughlin** [comment]
@fr1zle I've pinged over a skype request. Whenever you are free :)

**Comment by Hades32** [comment]
Teste and working great! Only function parameters don't show after I type the opening bracket.

When will this be merged? :)

**Comment by mat-mcloughlin** [comment]
Ok, 

as much as I keep trying I keep getting side tracked with other things atm. @fr1zle if you want to help I've given you access to the repository. please reach out so we can organise something

Thanks

**Comment by mat-mcloughlin** [comment]
I've pulled this in and published the build to the market place

**Comment by msaraiva** [comment]
@mat-mcloughlin and @fr1zle, I'm currently moving all the code in `atom-elixir/lib/alchemist-server/code/` into an separated project, so the code you have here is probably not going to be updated anymore. Actually there's already some changes on master (introspection of behavious/callbacks and some bug fixes). The good news is that after those changes, you'll be able to use the new server directly and get all the information already structured in JSON format. This will make the client implementation much simpler and easy to maintain. I could use both, Atom and VS Code to validate the new API, so please, let me know if you want to use it in this project. I've been testing/hacking VS Code for a week now and, for what I've seen, I could implement a lot of cool features in much less time than I could ever do for Atom.

Cheers.

**Comment by fr1zle** [comment]
@msaraiva sounds very interesting! I am definitely interested in collaborating on this.

**Comment by mat-mcloughlin** [comment]
@msaraiva count me in too

**Pull request merged**
