### PR TITLE
Copy language grammar and snippet jsons to out for "vsce package"

### PR DESCRIPTION
**Pull request by rkaramc**
#7
"vsce package" doesn't copy the grammar/snippet files to ./out. I have added gulp to copy these files over, and updated package.json to refer to the ./out/src/snippets and syntax files.

### CODE REVIEW

**Comment by fr1zle** [comment]
Theres no need for gulp. I have this issue fixed in my branch at https://github.com/fr1zle/vscode-elixir/tree/proper @mat-mcloughlin can you maybe cherry pick that one commit? It also replaces the syntax files with the official grammar (ported from the atom package) and fixes a few indendation problems.

I can also open a PR with a rebased commit later today if you'd prefer that.

**Comment by mat-mcloughlin** [comment]
@fr1zle there is a PR outstanding. Do I still need to cherry-pick or is that everything?

**Comment by fr1zle** [comment]
#9 can be merged. Already did the cherry picking just wanted you to :+1: :smiley:

**Comment by mat-mcloughlin** [comment]
No longer needed

**Pull request closed without merging**
