### PR TITLE
Adding support for comment toggle.

### PR DESCRIPTION
**Pull request by torrick**
Simple config change to enable the comment toggle functionality.

### CODE REVIEW

**Comment by aphillipo** [comment]
Nice!

**Comment by groksrc** [comment]
:shipit: 

I made the change manually for now and that fixes the problem. Please merge and push.

**Comment by mat-mcloughlin** [comment]
Hey guys, 

I've been busy with personal things. I'm back on with this now

Thanks for the PR @torrick

**Comment by groksrc** [comment]
:+1:

**Pull request merged**
