### PR TITLE
Single and double-quote surrounding pairs configuration

### PR DESCRIPTION
**Pull request by bill-mybiz**
When you highlight a word and press a single- or double-quote, it should wrap the selection with the quote. I've added the configuration I _believe_ is needed to effect this, as per looking at the [documentation](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages). ~~It is NOT tested!~~

~~I also am guessing at the escape character for the double-quote. (I'm not quite sure how to test this locally.)~~

EDIT: I've now tested it. See proceeding comment.

### CODE REVIEW

**Comment by Fahrradflucht** [comment]
@bill-mybiz There is actually quite good documentation on how to test and debug vscode extensions [here](https://code.visualstudio.com/docs/extensions/debugging-extensions)

**Comment by bill-mybiz** [comment]
Thanks @Fahrradflucht :smile:

Using that page that you so kindly provided, I went ahead and tested it:

* Debug the extension via "Launch Extension".
* Create a test_elixir.ex file.
* Type in some code and select a portion of text.
* Hit the single quote.
* It surrounds the text.
* Do the same for double quote.

```
defmodule Foo do
    def bar() do
        baz = selectme
    end
end
```

It does work for both single and double quotes. I also went ahead and reverted the changes to the original config file and then checked to be sure that the selection did _not_ occur.

**Comment by Fahrradflucht** [comment]
👍  LGTM

@mat-mcloughlin or @fr1zle I think this is save to merge.

**Comment by fr1zle** [comment]
Merged, tyvm @bill-mybiz

**Pull request merged**
