### PR TITLE
Add snippet for do/end blocks

### LINKED ISSUE #12: Autocomplete when typing `do`
When writing `do` the plugin wants to autocomplete to `doc`, so often end up deleting a doc comment I accidentally autocompleted, and if I want to avoid trailing whitespace I do a couple quick arrow strokes to get rid of the autocomplete prompt.

### PR DESCRIPTION
**Pull request by Fahrradflucht**
This fixes that annoying issue with the `doc` snippet firing every time one tries to write a do/end block.

Fixes #12

### CODE REVIEW

**Comment by fr1zle** [comment]
LGTM

@mat-mcloughlin thoughts?

**Comment by mat-mcloughlin** [comment]
+1 from me too. I'll pull it in later tonight and publish when I have access to a PC

**Comment by Fahrradflucht** [comment]
Gentle reminder. ☺️

**Comment by philipgiuliani** [comment]
Another gentle reminder. :relaxed:

**Pull request merged**
