### PR TITLE
Fix syntax-highlighting and add proper indentation fixes #5 #6 #7

### PR DESCRIPTION
**Pull request by fr1zle**
This fixes the issue that syntax-highlighting does not work in the build version of the extension.

Auto-Indentation has also been added.

String interpolation is now properly highlighted since we are using the official grammar from the elixir atom plugin now. EEX Templates are now supported as well.

### CODE REVIEW

**Comment by mat-mcloughlin** [comment]
There still seems to be an existing problem with the `elixirServer.ts` line 26

`const projectPath: string = path.join(vscode.workspace.rootPath);`

If you open up a single file then there is no workspace. Is it possible you can just check for the directory of the current file?

**Comment by fr1zle** [comment]
Hmm if the file is part of a project auto-complete wouldn't really work if the server only gets started in the files directory. But I think i will still implement it like that for now so that we don't get any crashes.

**Comment by fr1zle** [comment]
@mat-mcloughlin should be fixed

**Comment by philipgiuliani** [comment]
This also fixes #3 than :) So no issues left 💥

**Comment by philipgiuliani** [comment]
Works perfectly :)

**Pull request merged**
